// Single icon module: thin wrappers over lucide-react so every screen pulls from one place.
// Matches the vocabulary used by the old app/icons.jsx (`I.hash`, `I.lock`, `I.upload`, …)
// so migrations are a find-and-replace. Stroke-width 1.75 matches the design system.

import {
  Hash,
  Lock,
  Upload,
  Download,
  Paperclip,
  Play,
  Pause,
  Search,
  Bell,
  Settings,
  Plus,
  X,
  Image,
  MoreHorizontal,
  ChevronLeft,
  ChevronRight,
  Pin,
  Send,
  Smile,
  AtSign,
  Mic,
  Shield,
  Globe,
  Tag,
  Link as LinkIcon,
  User,
  Users,
  Folder,
  MessageSquare,
  LogOut,
  Film,
  File as FileIcon,
  Maximize,
  Volume2,
  Filter,
  Keyboard,
  Inbox,
  Check,
  AlertTriangle,
  Loader2,
  Copy,
  Trash2,
  type LucideProps,
} from "lucide-react";

const DEFAULTS: LucideProps = { strokeWidth: 1.75 as unknown as number, size: 16 };

// Convenient pre-sized wrapper to mimic window.DT.I shape used in the mocks.
// Usage: <Icon.hash /> or <Icon.upload size={14} />
function make<P extends LucideProps>(C: React.ComponentType<P>) {
  return (props: P) => <C {...(DEFAULTS as P)} {...props} />;
}

export const Icon = {
  hash: make(Hash),
  lock: make(Lock),
  upload: make(Upload),
  download: make(Download),
  paperclip: make(Paperclip),
  play: make(Play),
  pause: make(Pause),
  search: make(Search),
  bell: make(Bell),
  settings: make(Settings),
  plus: make(Plus),
  x: make(X),
  image: make(Image),
  moreH: make(MoreHorizontal),
  chevL: make(ChevronLeft),
  chevR: make(ChevronRight),
  pin: make(Pin),
  send: make(Send),
  smile: make(Smile),
  at: make(AtSign),
  mic: make(Mic),
  shield: make(Shield),
  globe: make(Globe),
  tag: make(Tag),
  link: make(LinkIcon),
  user: make(User),
  users: make(Users),
  folder: make(Folder),
  chat: make(MessageSquare),
  logout: make(LogOut),
  film: make(Film),
  file: make(FileIcon),
  maximize: make(Maximize),
  volume: make(Volume2),
  filter: make(Filter),
  kbd: make(Keyboard),
  inbox: make(Inbox),
  check: make(Check),
  warn: make(AlertTriangle),
  spinner: make(Loader2),
  copy: make(Copy),
  trash: make(Trash2),
};

export type IconName = keyof typeof Icon;
