// Migrated from app/files.jsx — Files table + detail rail + gallery grid +
// lightbox/video player. Data is fed from the Search API (empty query against
// the current workspace) plus the local upload queue.
//
// Phase 3 extras:
//   - Prefer thumbnailUrl (generated by the thumbnailer worker) for image /
//     video tiles when available; fall back to the old gradient placeholder.
//   - Table/Gallery view toggle. Gallery tile click opens a lightbox (images)
//     or a player overlay (videos). Esc + arrow keys + click-outside close.
//   - Shift-click on gallery tiles multi-selects; a toolbar strip appears when
//     >0 selected with Delete / Download / Copy link.

import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { fileApi, searchApi } from "@/api/endpoints";
import { fileVersionApi, shareLinkApi } from "@/api/adminApi";
import { useSession } from "@/store/session";
import { useUploads, formatBytes } from "@/lib/upload";
import { Icon } from "@/components/Icons";
import { toast } from "@/store/toast";

type FilterKey = "all" | "uploading" | "locked";
type ViewMode = "table" | "gallery";

const PLAYBACK_RATES: Array<[number, string]> = [
  [0.5, "½×"],
  [1, "1×"],
  [1.25, "1¼×"],
  [1.5, "1½×"],
  [2, "2×"],
];

export function FilesView() {
  const activeWs = useSession((s) => s.activeWorkspaceId);
  const [q, setQ] = useState("");
  const [filter, setFilter] = useState<FilterKey>("all");
  const [view, setView] = useState<ViewMode>("table");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [openId, setOpenId] = useState<string | null>(null);
  const [multi, setMulti] = useState<Set<string>>(new Set());
  const enqueue = useUploads((s) => s.enqueue);
  const jobs = useUploads((s) => s.jobs);
  const inputRef = useRef<HTMLInputElement>(null);
  const qc = useQueryClient();

  const filesQuery = useQuery({
    queryKey: ["files-search", activeWs, q],
    queryFn: () => searchApi.query({ q: q || "*", workspaceId: activeWs!, type: "file", limit: 100 }),
    enabled: Boolean(activeWs),
  });

  const detailQuery = useQuery({
    queryKey: ["file", selectedId],
    queryFn: () => fileApi.get(selectedId!),
    enabled: Boolean(selectedId),
  });
  const versionsQuery = useQuery({
    queryKey: ["file-versions", selectedId],
    queryFn: () => fileVersionApi.list(selectedId!),
    enabled: Boolean(selectedId),
  });
  const sharesQuery = useQuery({
    queryKey: ["file-shares", selectedId],
    queryFn: () => shareLinkApi.list(selectedId!),
    enabled: Boolean(selectedId),
  });
  const createShare = useMutation({
    mutationFn: (visibility: "public" | "workspace" | "restricted") => shareLinkApi.create(selectedId!, { visibility }),
    onSuccess: (r) => {
      void navigator.clipboard.writeText(r.url);
      toast("Share link created + copied");
      qc.invalidateQueries({ queryKey: ["file-shares", selectedId] });
    },
    onError: (e) => toast((e as Error).message, "error"),
  });
  const revokeShare = useMutation({
    mutationFn: (token: string) => shareLinkApi.revoke(token),
    onSuccess: () => {
      toast("Share link revoked");
      qc.invalidateQueries({ queryKey: ["file-shares", selectedId] });
    },
    onError: (e) => toast((e as Error).message, "error"),
  });

  const openQuery = useQuery({
    queryKey: ["file", openId],
    queryFn: () => fileApi.get(openId!),
    enabled: Boolean(openId),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => fileApi.remove(id),
  });

  const uploadingJobs = useMemo(
    () => Object.values(jobs).filter((j) => j.workspaceId === activeWs),
    [jobs, activeWs]
  );

  function handleFiles(files: FileList | null) {
    if (!files || !activeWs) return;
    for (const f of Array.from(files)) {
      if (f.size > 1024 * 1024 * 1024) {
        toast(`${f.name} is over the 1 GB cap`, "error");
        continue;
      }
      enqueue(f, activeWs);
    }
  }

  const allRows = useMemo(() => {
    const apiRows = (filesQuery.data?.files ?? []).map((f) => ({
      key: f.id,
      id: f.id as string | null,
      name: f.name,
      mime: f.mime,
      size: f.sizeBytes,
      thumbnailUrl: f.thumbnailUrl ?? null,
      status: "verified" as const,
      when: new Date(f.createdAt).toLocaleString(),
      hash: "",
    }));
    const uploadingRows = uploadingJobs
      .filter((j) => j.status !== "complete" && j.status !== "canceled")
      .map((j) => ({
        key: `job:${j.id}`,
        id: null,
        name: j.fileName,
        mime: j.mime,
        size: j.size,
        thumbnailUrl: null,
        status: j.status === "error" ? ("error" as const) : ("uploading" as const),
        pct: Math.floor(j.progress * 100),
        when: "just now",
        hash: "",
      }));
    return [...uploadingRows, ...apiRows].filter((r) => {
      if (filter === "uploading" && r.status !== "uploading") return false;
      if (filter === "locked" && r.status !== "verified") return false;
      return true;
    });
  }, [filesQuery.data, uploadingJobs, filter]);

  const mediaRows = useMemo(
    () => allRows.filter((r) => r.id && (r.mime.startsWith("image/") || r.mime.startsWith("video/"))),
    [allRows]
  );

  const kindOf = (mime: string) => (mime.split("/")[1] ?? "BIN").slice(0, 3).toUpperCase();
  const colorFor = (mime: string) => {
    if (mime.startsWith("video/")) return "var(--blood-500)";
    if (mime.startsWith("image/")) return "var(--lav-500)";
    if (mime.startsWith("audio/")) return "var(--mint-500)";
    if (mime.includes("pdf")) return "var(--blood-700)";
    if (mime.includes("zip") || mime.includes("archive")) return "var(--ink-500)";
    return "var(--ember-500)";
  };

  const totalSize = allRows.reduce((a, r) => a + r.size, 0);

  // Lightbox navigation: use mediaRows as the ordered list. Prev/next wrap.
  const openIndex = openId ? mediaRows.findIndex((m) => m.id === openId) : -1;
  const openRow = openIndex >= 0 ? mediaRows[openIndex] : null;

  function closeOpen() {
    setOpenId(null);
  }
  function step(delta: number) {
    if (mediaRows.length === 0) return;
    const base = openIndex >= 0 ? openIndex : 0;
    const next = (base + delta + mediaRows.length) % mediaRows.length;
    const nextRow = mediaRows[next];
    if (nextRow?.id) setOpenId(nextRow.id);
  }

  useEffect(() => {
    if (!openId) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") closeOpen();
      else if (e.key === "ArrowLeft") step(-1);
      else if (e.key === "ArrowRight") step(1);
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [openId, mediaRows.length]);

  function toggleMulti(id: string, e: React.MouseEvent) {
    if (!e.shiftKey) return false;
    e.preventDefault();
    e.stopPropagation();
    setMulti((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
    return true;
  }

  async function bulkDelete() {
    const ids = Array.from(multi);
    if (ids.length === 0) return;
    if (!window.confirm(`Delete ${ids.length} file${ids.length === 1 ? "" : "s"}?`)) return;
    await Promise.all(ids.map((id) => deleteMutation.mutateAsync(id).catch(() => null)));
    setMulti(new Set());
    qc.invalidateQueries({ queryKey: ["files-search"] });
    toast(`${ids.length} file${ids.length === 1 ? "" : "s"} deleted`);
  }

  async function bulkDownload() {
    const ids = Array.from(multi);
    for (const id of ids) {
      try {
        const f = await fileApi.get(id);
        const a = document.createElement("a");
        a.href = f.url;
        a.download = f.name;
        a.rel = "noreferrer";
        a.target = "_blank";
        document.body.appendChild(a);
        a.click();
        a.remove();
      } catch {
        // ignore individual failures; toast stays quiet for speed
      }
    }
  }

  async function bulkCopyLinks() {
    const ids = Array.from(multi);
    const urls: string[] = [];
    for (const id of ids) {
      try {
        const f = await fileApi.get(id);
        urls.push(f.url);
      } catch {}
    }
    if (urls.length === 0) return;
    await navigator.clipboard.writeText(urls.join("\n"));
    toast(`${urls.length} signed URL${urls.length === 1 ? "" : "s"} copied`);
  }

  return (
    <div className="page" style={{ display: "flex", flexDirection: "column" }}>
      <div className="page-head">
        <div className="title-block">
          <div className="caseno">CASE · FILES</div>
          <h1>
            Files
            <span style={{ color: "var(--fg3)", fontWeight: 400, fontSize: 14, marginLeft: 6, fontFamily: "var(--font-mono)" }}>
              {allRows.length} items · {formatBytes(totalSize)}
            </span>
          </h1>
        </div>
        <input className="input" placeholder="Search files…" value={q} onChange={(e) => setQ(e.target.value)} style={{ width: 220 }} />
        <div className="seg">
          {(
            [
              ["all", "All"],
              ["uploading", "Uploading"],
              ["locked", "Locked"],
            ] as [FilterKey, string][]
          ).map(([k, l]) => (
            <button key={k} className={filter === k ? "on" : ""} onClick={() => setFilter(k)}>
              {l}
            </button>
          ))}
        </div>
        <div className="seg">
          {(
            [
              ["table", "Table"],
              ["gallery", "Gallery"],
            ] as [ViewMode, string][]
          ).map(([k, l]) => (
            <button key={k} className={view === k ? "on" : ""} onClick={() => setView(k)}>
              {l}
            </button>
          ))}
        </div>
        <input ref={inputRef} type="file" multiple hidden onChange={(e) => handleFiles(e.target.files)} />
        <button className="btn btn-primary" onClick={() => inputRef.current?.click()}>
          <Icon.upload size={14} /> Upload
        </button>
      </div>

      {multi.size > 0 && (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            padding: "8px 24px",
            background: "var(--ember-50)",
            borderBottom: "1px solid var(--border-soft)",
          }}
        >
          <span className="caseno">{multi.size} SELECTED</span>
          <div style={{ flex: 1 }} />
          <button className="btn btn-secondary" onClick={bulkDownload}>
            <Icon.download size={14} /> Download
          </button>
          <button className="btn btn-secondary" onClick={bulkCopyLinks}>
            <Icon.link size={14} /> Copy link
          </button>
          <button className="btn btn-secondary" onClick={bulkDelete}>
            <Icon.trash size={14} /> Delete
          </button>
          <button className="tb-btn" onClick={() => setMulti(new Set())}>
            <Icon.x size={14} />
          </button>
        </div>
      )}

      <div style={{ flex: 1, display: "grid", gridTemplateColumns: selectedId ? "1fr 360px" : "1fr", minHeight: 0 }}>
        <div style={{ overflow: "auto", padding: "12px 24px 24px" }}>
          {view === "table" ? (
            <table style={{ width: "100%", borderCollapse: "collapse", font: "400 13px/1.3 var(--font-sans)" }}>
              <thead>
                <tr>
                  {["Name", "Size", "Status", "Modified", ""].map((h) => (
                    <th
                      key={h}
                      style={{
                        textAlign: "left",
                        font: "500 10px/1 var(--font-mono)",
                        letterSpacing: ".14em",
                        textTransform: "uppercase",
                        color: "var(--fg3)",
                        padding: "0 10px 8px",
                        borderBottom: "1px solid var(--border-soft)",
                      }}
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {allRows.map((r) => {
                  const selected = r.id ? multi.has(r.id) : false;
                  return (
                    <tr
                      key={r.key}
                      onClick={(e) => {
                        if (!r.id) return;
                        if (toggleMulti(r.id, e)) return;
                        setSelectedId(r.id);
                      }}
                      style={{
                        cursor: r.id ? "pointer" : "default",
                        background: selected
                          ? "var(--ember-100, var(--ember-50))"
                          : selectedId === r.id
                          ? "var(--ember-50)"
                          : "transparent",
                      }}
                    >
                      <td style={{ padding: 10, borderBottom: "1px solid var(--border-soft)" }}>
                        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                          {r.thumbnailUrl ? (
                            <img
                              src={r.thumbnailUrl}
                              alt=""
                              style={{ width: 30, height: 30, borderRadius: 5, objectFit: "cover", flexShrink: 0 }}
                            />
                          ) : (
                            <div
                              style={{
                                width: 30,
                                height: 30,
                                borderRadius: 5,
                                background: colorFor(r.mime),
                                color: "#fff",
                                font: "700 9px/30px var(--font-mono)",
                                textAlign: "center",
                                flexShrink: 0,
                              }}
                            >
                              {kindOf(r.mime)}
                            </div>
                          )}
                          <span style={{ fontWeight: 500 }}>{r.name}</span>
                        </div>
                      </td>
                      <td
                        style={{
                          padding: 10,
                          borderBottom: "1px solid var(--border-soft)",
                          color: "var(--fg2)",
                          fontFamily: "var(--font-mono)",
                          fontSize: 12,
                        }}
                      >
                        {formatBytes(r.size)}
                      </td>
                      <td style={{ padding: 10, borderBottom: "1px solid var(--border-soft)" }}>
                        {r.status === "uploading" ? (
                          <span className="chip warn">
                            <span className="dot" />
                            {"pct" in r ? r.pct : 0}%
                          </span>
                        ) : r.status === "error" ? (
                          <span className="chip danger">
                            <span className="dot" />
                            ERROR
                          </span>
                        ) : (
                          <span className="chip success">
                            <span className="dot" />
                            VERIFIED
                          </span>
                        )}
                      </td>
                      <td style={{ padding: 10, borderBottom: "1px solid var(--border-soft)", color: "var(--fg3)" }}>{r.when}</td>
                      <td style={{ padding: 10, borderBottom: "1px solid var(--border-soft)", textAlign: "right" }}>
                        <button className="tb-btn">
                          <Icon.moreH size={14} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
                {allRows.length === 0 && !filesQuery.isLoading && (
                  <tr>
                    <td colSpan={5}>
                      <div className="empty">
                        <div className="title">No files yet.</div>
                        <div className="sub">Drag a file here, or hit Upload. Every chunk is sha256-verified.</div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px,1fr))", gap: 8 }}>
              {allRows.map((r) => {
                const isImage = r.mime.startsWith("image/");
                const isVideo = r.mime.startsWith("video/");
                const canOpen = Boolean(r.id) && (isImage || isVideo);
                const selected = r.id ? multi.has(r.id) : false;
                return (
                  <div
                    key={r.key}
                    onClick={(e) => {
                      if (!r.id) return;
                      if (toggleMulti(r.id, e)) return;
                      if (canOpen) setOpenId(r.id);
                      else setSelectedId(r.id);
                    }}
                    style={{
                      aspectRatio: 1,
                      borderRadius: 8,
                      cursor: r.id ? "pointer" : "default",
                      position: "relative",
                      overflow: "hidden",
                      border: selected
                        ? "2px solid var(--ember-500)"
                        : selectedId === r.id
                        ? "2px solid var(--ember-500)"
                        : "1px solid var(--border-soft)",
                      background: r.thumbnailUrl
                        ? `center/cover no-repeat url(${JSON.stringify(r.thumbnailUrl)})`
                        : isImage
                        ? "linear-gradient(135deg, #8B6BF0, #5E3DC7)"
                        : isVideo
                        ? "linear-gradient(135deg, #1E2247, #5E3DC7)"
                        : "var(--paper-50)",
                      color: isImage || isVideo ? "#fff" : "var(--fg1)",
                    }}
                  >
                    {isVideo && (
                      <div
                        style={{
                          position: "absolute",
                          top: "50%",
                          left: "50%",
                          transform: "translate(-50%,-50%)",
                          width: 36,
                          height: 36,
                          borderRadius: 999,
                          background: "rgba(255,253,248,.9)",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          color: "var(--ink-900)",
                        }}
                      >
                        <Icon.play size={16} />
                      </div>
                    )}
                    {!isImage && !isVideo && (
                      <div
                        style={{
                          position: "absolute",
                          top: 10,
                          left: 10,
                          width: 30,
                          height: 30,
                          borderRadius: 5,
                          background: colorFor(r.mime),
                          color: "#fff",
                          font: "700 9px/30px var(--font-mono)",
                          textAlign: "center",
                        }}
                      >
                        {kindOf(r.mime)}
                      </div>
                    )}
                    <div
                      style={{
                        position: "absolute",
                        bottom: 0,
                        left: 0,
                        right: 0,
                        padding: "14px 8px 6px",
                        background: isImage || isVideo ? "linear-gradient(transparent, rgba(14,17,48,.7))" : "transparent",
                        color: isImage || isVideo ? "#fff" : "var(--fg2)",
                        font: "500 10px/1.1 var(--font-mono)",
                        display: "flex",
                        justifyContent: "space-between",
                        gap: 8,
                      }}
                    >
                      <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.name}</span>
                      <span>{formatBytes(r.size)}</span>
                    </div>
                  </div>
                );
              })}
              {allRows.length === 0 && !filesQuery.isLoading && (
                <div className="empty" style={{ gridColumn: "1 / -1" }}>
                  <div className="title">No files yet.</div>
                  <div className="sub">Drag a file here, or hit Upload. Every chunk is sha256-verified.</div>
                </div>
              )}
            </div>
          )}
        </div>

        {selectedId && detailQuery.data && (
          <div style={{ borderLeft: "1px solid var(--border-soft)", background: "var(--paper-0)", padding: 16, overflow: "auto" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <strong>File details</strong>
              <div style={{ flex: 1 }} />
              <button className="tb-btn" onClick={() => setSelectedId(null)}>
                <Icon.x size={14} />
              </button>
            </div>
            <div
              style={{
                marginTop: 14,
                aspectRatio: "4/3",
                borderRadius: 10,
                background: detailQuery.data.thumbnailUrl
                  ? `center/cover no-repeat url(${JSON.stringify(detailQuery.data.thumbnailUrl)})`
                  : "linear-gradient(135deg, #1E2247, #5E3DC7)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#fff",
              }}
            >
              {!detailQuery.data.thumbnailUrl && (
                <div
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 999,
                    background: "rgba(255,253,248,.9)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "var(--ink-900)",
                  }}
                >
                  <Icon.play size={18} />
                </div>
              )}
            </div>
            <div style={{ font: "600 16px/1.2 var(--font-sans)", marginTop: 14 }}>{detailQuery.data.name}</div>
            <div className="caseno" style={{ marginTop: 6 }}>
              {formatBytes(detailQuery.data.sizeBytes).toUpperCase()} · {new Date(detailQuery.data.createdAt).toLocaleString().toUpperCase()}
            </div>
            <div style={{ marginTop: 14, display: "grid", gap: 10 }}>
              {[
                ["Mime", detailQuery.data.mime],
                ["sha256", detailQuery.data.checksum],
                ["Version", `v${detailQuery.data.version}`],
              ].map(([k, v]) => (
                <div key={k} style={{ display: "flex", justifyContent: "space-between", fontSize: 12, gap: 10 }}>
                  <span style={{ color: "var(--fg3)" }}>{k}</span>
                  <span
                    style={{
                      fontFamily: k === "sha256" ? "var(--font-mono)" : "inherit",
                      textAlign: "right",
                      wordBreak: "break-all",
                    }}
                  >
                    {v}
                  </span>
                </div>
              ))}
            </div>
            <div style={{ display: "flex", gap: 6, marginTop: 14 }}>
              <a href={detailQuery.data.url} target="_blank" rel="noreferrer" className="btn btn-primary" style={{ flex: 1, justifyContent: "center" }}>
                <Icon.download size={14} /> Download
              </a>
              <button
                className="btn btn-secondary"
                onClick={() => {
                  void navigator.clipboard.writeText(detailQuery.data!.url);
                  toast("Signed URL copied (valid 15 min)");
                }}
              >
                <Icon.link size={14} />
              </button>
            </div>

            {/* Versions */}
            <div style={{ marginTop: 22 }}>
              <div className="caseno" style={{ marginBottom: 6 }}>
                VERSIONS · {versionsQuery.data?.items.length ?? 0}
              </div>
              <div style={{ display: "grid", gap: 6 }}>
                {versionsQuery.data?.items.map((v) => (
                  <div key={v.id} style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12 }}>
                    <span className="caseno" style={{ width: 38 }}>
                      v{v.version}
                    </span>
                    <span style={{ flex: 1, fontFamily: "var(--font-mono)", color: "var(--fg3)" }}>
                      {v.checksum.slice(0, 10)}…
                    </span>
                    <span style={{ color: "var(--fg3)" }}>{formatBytes(v.sizeBytes)}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Share links */}
            <div style={{ marginTop: 22 }}>
              <div className="caseno" style={{ marginBottom: 6, display: "flex", alignItems: "center" }}>
                <span>SHARE LINKS · {sharesQuery.data?.items.length ?? 0}</span>
                <div style={{ flex: 1 }} />
                <button
                  className="btn btn-ghost"
                  style={{ padding: "2px 6px", fontSize: 10 }}
                  onClick={() => createShare.mutate("workspace")}
                  disabled={createShare.isPending}
                >
                  + Create
                </button>
              </div>
              <div style={{ display: "grid", gap: 8 }}>
                {sharesQuery.data?.items.map((s) => (
                  <div key={s.id} style={{ padding: 8, border: "1px solid var(--border-soft)", borderRadius: 6, fontSize: 12 }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                      <span className="chip">
                        <span className="dot" />
                        {s.visibility.toUpperCase()}
                      </span>
                      <div style={{ flex: 1 }} />
                      <button
                        className="tb-btn"
                        onClick={() => {
                          void navigator.clipboard.writeText(s.url);
                          toast("Copied");
                        }}
                      >
                        <Icon.copy size={12} />
                      </button>
                      <button className="tb-btn" style={{ color: "var(--blood-700)" }} onClick={() => revokeShare.mutate(s.token)}>
                        <Icon.trash size={12} />
                      </button>
                    </div>
                    <div style={{ marginTop: 4, fontFamily: "var(--font-mono)", color: "var(--fg3)", wordBreak: "break-all" }}>{s.url}</div>
                  </div>
                ))}
                {(sharesQuery.data?.items.length ?? 0) === 0 && <div className="hint">No active share links.</div>}
              </div>
            </div>
          </div>
        )}
      </div>

      {openId && openRow && (
        <Lightbox
          row={openRow}
          file={openQuery.data ?? null}
          onClose={closeOpen}
          onPrev={() => step(-1)}
          onNext={() => step(1)}
        />
      )}
    </div>
  );
}

function Lightbox({
  row,
  file,
  onClose,
  onPrev,
  onNext,
}: {
  row: { id: string | null; name: string; mime: string; size: number; thumbnailUrl: string | null };
  file: { url: string; mime: string; name: string } | null;
  onClose: () => void;
  onPrev: () => void;
  onNext: () => void;
}) {
  const isVideo = row.mime.startsWith("video/");
  const videoRef = useRef<HTMLVideoElement>(null);
  const [rate, setRate] = useState(1);

  useEffect(() => {
    if (videoRef.current) videoRef.current.playbackRate = rate;
  }, [rate, file?.url]);

  return (
    <div
      className="modal-backdrop"
      onClick={onClose}
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(14,17,48,.85)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 80,
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{ position: "relative", maxWidth: "90vw", maxHeight: "90vh", display: "flex", flexDirection: "column", gap: 10 }}
      >
        {isVideo ? (
          file?.url ? (
            <video
              ref={videoRef}
              src={file.url}
              controls
              autoPlay
              muted
              style={{ maxWidth: "90vw", maxHeight: "78vh", background: "#000", borderRadius: 12 }}
            />
          ) : (
            <div style={{ padding: 40, color: "#fff" }}>Loading…</div>
          )
        ) : (
          <img
            src={file?.url ?? row.thumbnailUrl ?? undefined}
            alt={row.name}
            style={{ maxWidth: "90vw", maxHeight: "82vh", borderRadius: 12, background: "#000" }}
          />
        )}

        {isVideo && (
          <div style={{ display: "flex", alignItems: "center", gap: 6, justifyContent: "center" }}>
            {PLAYBACK_RATES.map(([r, label]) => (
              <button
                key={r}
                className={rate === r ? "btn btn-primary" : "btn btn-secondary"}
                onClick={() => setRate(r)}
                style={{ minWidth: 48, justifyContent: "center" }}
              >
                {label}
              </button>
            ))}
          </div>
        )}

        <div style={{ position: "absolute", top: 14, right: 14, display: "flex", gap: 6 }}>
          {file?.url && (
            <a href={file.url} download={row.name} className="btn btn-secondary">
              <Icon.download size={14} />
            </a>
          )}
          <button className="btn btn-secondary" onClick={onClose}>
            <Icon.x size={14} />
          </button>
        </div>

        <div
          style={{
            position: "absolute",
            bottom: isVideo ? 60 : 14,
            left: 14,
            right: 14,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            color: "#fff",
            pointerEvents: "none",
          }}
        >
          <div style={{ pointerEvents: "auto" }}>
            <div style={{ font: "600 14px/1 var(--font-sans)" }}>{row.name}</div>
            <div style={{ font: "400 11px/1 var(--font-mono)", opacity: 0.8, marginTop: 4 }}>
              {formatBytes(row.size)} · {row.mime}
            </div>
          </div>
          <div style={{ display: "flex", gap: 8, pointerEvents: "auto" }}>
            <button
              className="tb-btn"
              style={{ background: "rgba(14,17,48,.6)", color: "#fff" }}
              onClick={(e) => {
                e.stopPropagation();
                onPrev();
              }}
            >
              <Icon.chevL size={14} />
            </button>
            <button
              className="tb-btn"
              style={{ background: "rgba(14,17,48,.6)", color: "#fff" }}
              onClick={(e) => {
                e.stopPropagation();
                onNext();
              }}
            >
              <Icon.chevR size={14} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
